[package]
name = "DGPCRRewrite"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
eframe = { version = "0.31.1", features = ["wgpu"] }

egui = "0.31.1"
image = "0.25.6"
